# SPDX-License-Identifier: GPL-2.0-only

[package]
name = "reveille-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reveille-core = { path = "../reveille-core" }
reveille-platform = { path = "../reveille-platform" }
serde.workspace = true
tauri = { version = "2", features = [] }
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
